apiVersion: v1
kind: Pod
metadata:
 name: node-anti-affinity-demo
spec:
 affinity:
  nodeAffinity:
   requiredDuringSchedulingIgnoreDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: hardware
        operator: NotIn
        values:
        - hdd
 containers:
 - name: nginx
   image: nginx