apiVersion: v1
kind: Pod
metadata: 
 name: pod-1
 labels: 
  appname: pod-1
  purpose: pod-anti-affinity-demo
spec:
 containers:
 - name: nginx
   image: nginx


---
apiVersion: v1
kind: Pod
metadata: 
 name: pod-2
 labels:
  appname: pod-2
  purpose: pod-anti-affinity-demo
spec:
 affinity:
  podAntiAffinity:
   requiredDuringSchedulingIgnoreDuringExecution:
   - labelselectors:
      matchExpressions:
      - key: appname
        operator: In
        values:
        - pod-1
     topologyKey: "kubernetes.io/hostname"
 containers:
 - name: nginx
   image: nginx

