apiVersion: v1 
kind: Pod
metadata:
 namespace: roboshop
 name: taint-toleration
spec:
 nodeSelector:
  disktype: hdd
 containers:
 - name: nginx
   image: nginx
 tolerations:
 - key: "key"
   operator: "Equal"
   value: "value"
   effect: NoExecute
















